### ISSUE TITLE
License

### ISSUE THREAD

**Issue by WoLfMaN86** [RamonWill/price-comparison-project#1]
Hey there!

First of all thank you for the work you published, I am a student working on something similar, I would like to know if you could be so kind to include a "License" to your project, GNU GENERAL PUBLIC LICENSE, MIT license, or whatever you think it would suit better. 

Thanks in advance,

Diego

**Comment by RamonWill** [comment]
Hi Diego,
Sure thing, this has been actioned
regards,
Ramon
